Fix pool maxsize unlimited
aio-libs/aiomysql pull request #426
Opened 2019-08-11 16:55 UTC by d-ryzhikov

## What do these changes do?

Fix `pool.maxsize` logic to allow pool's size to be unlimited when `maxsize` is 0.
https://aiomysql.readthedocs.io/en/latest/pool.html#Pool

## Are there changes in behavior for the user?

No changes.

## Related issue number

https://github.com/aio-libs/aiomysql/issues/119

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

2020-11-16 10:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aio-libs/aiomysql?pullRequest=426) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aio-libs/aiomysql?pullRequest=426) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aio-libs/aiomysql?pullRequest=426) it.</sub>

2022-01-28 21:09 UTC, Nothing4You requested changes
thank you for the PR.

effectively this PR should be porting https://github.com/aio-libs/aiopg/pull/59

i've added another test case that fails on this PR, this change should be ported as well:
https://github.com/aio-libs/aiopg/pull/59/files#diff-34274c292424cfc2c3ac7e6a8a625f4d2cc652639b0bcaab02978bdf5bad6520R42

2022-02-02 03:09 UTC, d-ryzhikov commented on aiomysql/pool.py
> +        return self._free.maxlen or float("inf")
Fixed.
However, the behavior in aiopg is faulty: whenever a connection from a pool with `minsize=0, maxsize=0` is acquired, it blocks forever. I created a PR to fix it there: https://github.com/aio-libs/aiopg/pull/888.
These changes where also duplicated in this PR: https://github.com/aio-libs/aiomysql/pull/426/files#diff-9ccf7da6bb12e81af8f2eefbd1c5b43ebc6695d4d750a29683e90024156bc03fR185.

2022-02-02 21:33 UTC, Nothing4You commented on aiomysql/pool.py
> +        return self._free.maxlen or float("inf")
thanks!

2022-02-02 21:42 UTC, Nothing4You approved these changes

2022-02-02 21:57 UTC, merged