Update examples to use async/await
aio-libs/aiomysql pull request #582
Opened 2021-05-04 11:27 UTC by anand2312

Closes #570

This pull request updates the examples in the documentation to use `async/await` syntax instead of the old `@asyncio.coroutine` syntax.

2022-01-02 16:03 UTC, H4ckerxx44 commented
Why is this not merged yet? It's quite painful to have examples very out of date..

2022-01-02 17:24 UTC, anand2312 commented
@H4ckerxx44 
This project is dead :(

2022-01-02 17:33 UTC, H4ckerxx44 commented
That's quite sad, thanks for the response though!

2022-01-16 18:20 UTC, Nothing4You requested changes
thanks for the PR, I've left a few comments requesting changes, one they are applied I will merge this.

I haven't tested the updated examples but the changes look good.
I plan to do a proper review of the examples before the next release.

2022-01-16 18:20 UTC, Nothing4You commented on docs/cursors.rst
>          def test_example():
this should be async now

2022-01-16 18:20 UTC, Nothing4You commented on docs/connection.rst
>                                             user='root', password='', db='mysql',
indent no longer matches

2022-01-16 18:20 UTC, Nothing4You commented on docs/cursors.rst
>                                                 user='root', password='',
indent no longer matches

2022-01-16 18:20 UTC, Nothing4You commented on docs/cursors.rst
>                                                 user='root', password='',
indent no longer matches

2022-01-16 18:20 UTC, Nothing4You commented on docs/cursors.rst
>                                     BEGIN
indent no longer matches

2022-01-16 18:20 UTC, Nothing4You commented on docs/cursors.rst
>                                                 user='root', password='',
indent no longer matches

2022-01-16 18:20 UTC, Nothing4You commented on docs/cursors.rst
>                                                 user='root', password='',
indent no longer matches

2022-01-16 18:20 UTC, Nothing4You commented on docs/pool.rst
>                                                 user='root', password='',
indent no longer matches

2022-01-21 16:49 UTC, Nothing4You approved these changes
implemented requested changes

2022-01-21 16:49 UTC, merged