Update build-system requirements of setuptools-scm to >= 7.0.5
aio-libs/aiomysql pull request #872
Opened 2022-11-18 19:17 UTC by dvzrv

pyproject.toml:
Increase the build-system requirements of setuptools-scm to >= 7.0.5, which obsoletes setuptools-scm-git-archive.
Issues around the use of setuptools-scm as discussed in https://github.com/aio-libs/aiomysql/issues/809 and https://github.com/pypa/setuptools_scm/issues/745
have been fixed in
https://github.com/pypa/setuptools_scm/commit/b7c0d0d04cd7fdd761eabcd3d16ce18b12d458d7 and relesed with
https://github.com/pypa/setuptools_scm/releases/tag/v7.0.5

## What do these changes do?

Increase the build-system requirements of setuptools-scm to >= 7.0.5, which obsoletes setuptools-scm-git-archive.

## Are there changes in behavior for the user?

setuptools-scm-git-archive is no longer required during build time.

## Related issue number
https://github.com/aio-libs/aiomysql/issues/809 
https://github.com/pypa/setuptools_scm/issues/745

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

2022-12-06 16:55 UTC, dvzrv commented
@Nothing4You since you seem to be the most active recently, could you have a look and merge this please? :)
We would like to drop the use of setuptools-scm-git-archive on Arch Linux :)

2022-12-06 17:08 UTC, Nothing4You commented
thanks for the PR, I'll get to it soonish

2023-01-02 15:10 UTC, dvzrv commented
> thanks for the PR, I'll get to it soonish

@Nothing4You anything more I can do? Is the change okay this way?

2023-05-27 23:01 UTC, webknjaz requested changes
This is missing updates to `.git_archival.txt` that the new version relies on.

2025-09-22 00:17 UTC, Nothing4You commented
thanks, setuptools-scm has since been updated an will support >=7.0.5 in the next release

2025-09-22 00:17 UTC, closed without merging